class_path: a_priori_snr.models.a_priori_snr_tcn.APrioriSNREstimator
init_args:
  learning_rate: 0.001
  batch_size: 8
  metrics_test: ""
  metrics_val: ""
  frame_length: 1024
  shift_length: 512
  window_type: hann
  layer: 6
  stack: 2
  kernel: 3
  hidden_dim: null
  fs: 16000
  use_batchnorm: false
  use_log: true
  limit_frequencies: false
  my_lr_scheduler: OneCycleLR
